name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install --frozen-lockfile
          start: yarn start
          wait-on: http://localhost:3000
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }},
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }},
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }},
          REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }},
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }},
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }},
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }},
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }},
      - name: Gerar relatorio
        run: cd cypress && node report.js
      - name: Fazer upload do relatorio
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: cypress/cucumber-report/
